export const languages = [
  { code: "ace", name: "Acehnese" },
  { code: "af", name: "Afrikaans" },
  { code: "ak", name: "Akan" },
  { code: "sq", name: "Albanian" },
  { code: "am", name: "Amharic" },
  { code: "ar", name: "Arabic" },
  { code: "hy", name: "Armenian" },
  { code: "as", name: "Assamese" },
  { code: "ast", name: "Asturian" },
  { code: "awa", name: "Awadhi" },
  { code: "quy", name: "Ayacucho Quechua" },
  { code: "ayr", name: "Aymara, Central" },
  { code: "az", name: "Azerbaijani" },
  { code: "azj", name: "Azerbaijani, Northern" },
  { code: "azb", name: "Azerbaijani, Southern" },
  { code: "ban", name: "Balinese" },
  { code: "bm", name: "Bambara" },
  { code: "bjn", name: "Banjar" },
  { code: "ba", name: "Bashkir" },
  { code: "be", name: "Belarusian" },
  { code: "bem", name: "Bemba" },
  { code: "bn", name: "Bengali" },
  { code: "bho", name: "Bhojpuri" },
  { code: "bs", name: "Bosnian" },
  { code: "bug", name: "Buginese" },
  { code: "bg", name: "Bulgarian" },
  { code: "ca", name: "Catalan" },
  { code: "ceb", name: "Cebuano" },
  { code: "hne", name: "Chhattisgarhi" },
  { code: "zh-CN", name: "Chinese (Simplified)" },
  { code: "zh-TW", name: "Chinese (Traditional)" },
  { code: "cjk", name: "Chokwe" },
  { code: "crh", name: "Crimean Tatar" },
  { code: "hr", name: "Croatian" },
  { code: "cs", name: "Czech" },
  { code: "da", name: "Danish" },
  { code: "prs", name: "Dari" },
  { code: "diq", name: "Dimli" },
  { code: "dik", name: "Dinka, Southwestern" },
  { code: "nl", name: "Dutch" },
  { code: "dyu", name: "Dyula" },
  { code: "dz", name: "Dzongkha" },
  { code: "en", name: "English" },
  { code: "eo", name: "Esperanto" },
  { code: "et", name: "Estonian" },
  { code: "ee", name: "Ewe" },
  { code: "fo", name: "Faroese" },
  { code: "fj", name: "Fijian" },
  { code: "fi", name: "Finnish" },
  { code: "fon", name: "Fon" },
  { code: "fr", name: "French" },
  { code: "fur", name: "Friulian" },
  { code: "gl", name: "Galician" },
  { code: "lg", name: "Ganda" },
  { code: "ka", name: "Georgian" },
  { code: "de", name: "German" },
  { code: "el", name: "Greek" },
  { code: "gn", name: "Guarani" },
  { code: "gu", name: "Gujarati" },
  { code: "ht", name: "Haitian" },
  { code: "khk", name: "Halh Mongolian" },
  { code: "ha", name: "Hausa" },
  { code: "he", name: "Hebrew" },
  { code: "hi", name: "Hindi" },
  { code: "hu", name: "Hungarian" },
  { code: "is", name: "Icelandic" },
  { code: "ig", name: "Igbo" },
  { code: "ilo", name: "Iloko" },
  { code: "id", name: "Indonesian" },
  { code: "ga", name: "Irish" },
  { code: "it", name: "Italian" },
  { code: "ja", name: "Japanese" },
  { code: "jv", name: "Javanese" },
  { code: "kac", name: "Jingpho" },
  { code: "kbp", name: "Kabiyè" },
  { code: "kea", name: "Kabuverdianu" },
  { code: "kab", name: "Kabyle" },
  { code: "kam", name: "Kamba" },
  { code: "kn", name: "Kannada" },
  { code: "knc", name: "Kanuri, Central (Latin script)" },
  { code: "kas", name: "Kashmiri (Arabic script)" },
  { code: "ks", name: "Kashmiri (Devanagari script)" },
  { code: "kk", name: "Kazakh" },
  { code: "km", name: "Khmer" },
  { code: "ki", name: "Kikuyu" },
  { code: "kmb", name: "Kimbundu" },
  { code: "rw", name: "Kinyarwanda" },
  { code: "kg", name: "Kongo" },
  { code: "ko", name: "Korean" },
  { code: "ckb", name: "Kurdish, Central" },
  { code: "kmr", name: "Kurdish, Northern" },
  { code: "ky", name: "Kyrgyz" },
  { code: "lo", name: "Lao" },
  { code: "ltg", name: "Latgalian" },
  { code: "la", name: "Latin" },
  { code: "lv", name: "Latvian" },
  { code: "lij", name: "Ligurian" },
  { code: "li", name: "Limburgish" },
  { code: "ln", name: "Lingala" },
  { code: "lt", name: "Lithuanian" },
  { code: "lmo", name: "Lombard" },
  { code: "lua", name: "Luba-Kasai" },
  { code: "luo", name: "Luo" },
  { code: "lb", name: "Luxembourgish" },
  { code: "mk", name: "Macedonian" },
  { code: "mag", name: "Magahi" },
  { code: "mai", name: "Maithili" },
  { code: "mg", name: "Malagasy" },
  { code: "ms", name: "Malay" },
  { code: "ml", name: "Malayalam" },
  { code: "mt", name: "Maltese" },
  { code: "mni", name: "Manipuri" },
  { code: "mi", name: "Maori" },
  { code: "mr", name: "Marathi" },
  { code: "min", name: "Minangkabau" },
  { code: "lus", name: "Mizo" },
  { code: "mn", name: "Mongolian (Traditional)" },
  { code: "mos", name: "Mossi" },
  { code: "my", name: "Myanmar (Burmese)" },
  { code: "ne", name: "Nepali" },
  { code: "fuv", name: "Nigerian Fulfulde" },
  { code: "nb", name: "Norwegian (Bokmål)" },
  { code: "nn", name: "Norwegian (Nynorsk)" },
  { code: "nus", name: "Nuer" },
  { code: "ny", name: "Nyanja" },
  { code: "oc", name: "Occitan" },
  { code: "or", name: "Odia (Oriya)" },
  { code: "gaz", name: "Oromo, West Central" },
  { code: "pag", name: "Pangasinan" },
  { code: "pap", name: "Papiamento" },
  { code: "pbt", name: "Pashto, Southern" },
  { code: "ps", name: "Pashto" },
  { code: "pes", name: "Persian, Western" },
  { code: "plt", name: "Plateau Malagasy" },
  { code: "pl", name: "Polish" },
  { code: "pt-BR", name: "Portuguese (Brazil)" },
  { code: "pt-PT", name: "Portuguese (Portugal)" },
  { code: "pa", name: "Punjabi" },
  { code: "ro", name: "Romanian" },
  { code: "rn", name: "Rundi" },
  { code: "ru", name: "Russian" },
  { code: "sm", name: "Samoan" },
  { code: "sg", name: "Sango" },
  { code: "sa", name: "Sanskrit" },
  { code: "sat", name: "Santali" },
  { code: "sc", name: "Sardinian" },
  { code: "gd", name: "Scots Gaelic" },
  { code: "sr-Cyrl", name: "Serbian (Cyrillic)" },
  { code: "sr-Latn", name: "Serbian (Latin)" },
  { code: "shn", name: "Shan" },
  { code: "sn", name: "Shona" },
  { code: "scn", name: "Sicilian" },
  { code: "szl", name: "Silesian" },
  { code: "sd", name: "Sindhi" },
  { code: "si", name: "Sinhala" },
  { code: "sk", name: "Slovak" },
  { code: "sl", name: "Slovenian" },
  { code: "so", name: "Somali" },
  { code: "nso", name: "Sotho, Northern" },
  { code: "st", name: "Sotho, Southern" },
  { code: "es-ES", name: "Spanish" },
  { code: "es-419", name: "Spanish (Latin America)" },
  { code: "lvs", name: "Standard Latvian" },
  { code: "zsm", name: "Standard Malay" },
  { code: "su", name: "Sundanese" },
  { code: "sw", name: "Swahili" },
  { code: "ss", name: "Swati" },
  { code: "sv", name: "Swedish" },
  { code: "tl", name: "Tagalog" },
  { code: "tg", name: "Tajik" },
  { code: "taq", name: "Tamasheq" },
  { code: "tzm", name: "Tamazight, Central Atlas" },
  { code: "ta", name: "Tamil" },
  { code: "tt", name: "Tatar" },
  { code: "te", name: "Telugu" },
  { code: "th", name: "Thai" },
  { code: "bo", name: "Tibetan" },
  { code: "ti", name: "Tigrinya" },
  { code: "tpi", name: "Tok Pisin" },
  { code: "als", name: "Tosk Albanian" },
  { code: "ts", name: "Tsonga" },
  { code: "tn", name: "Tswana" },
  { code: "tum", name: "Tumbuka" },
  { code: "tr", name: "Turkish" },
  { code: "tk", name: "Turkmen" },
  { code: "tw", name: "Twi" },
  { code: "uk", name: "Ukrainian" },
  { code: "umb", name: "Umbundu" },
  { code: "ur", name: "Urdu" },
  { code: "ug", name: "Uyghur" },
  { code: "uzn", name: "Uzbek, Northern" },
  { code: "vec", name: "Venetian" },
  { code: "vi", name: "Vietnamese" },
  { code: "war", name: "Waray (Philippines)" },
  { code: "cy", name: "Welsh" },
  { code: "wo", name: "Wolof" },
  { code: "xh", name: "Xhosa" },
  { code: "ydd", name: "Yiddish, Eastern" },
  { code: "yo", name: "Yoruba" },
  { code: "zu", name: "Zulu" },
];
